@startuml Restauraunt
Class restauraunt {
    name String
    imageURL [[ link]]
    location String
    menus Array <menu>
    addmenu(<menu>)
    deleteMenu(<menu>)
}

Class menu {
    title String
    icon String
    items Array<item>
    additem(<item>)
    deleteItem(<item>)
}

Class Item {
    name String
    price Number
    createItem(title, price)
    deleteItem()
}

restauraunt --{menu
menu --{Item


@enduml